### ISSUE TITLE
第一人称下不是正对窗户的

### ISSUE THREAD

**Issue by FuBangkun** [Arrokoth486958/Legacy-Rocket-Model#1]
二阶火箭第一人称下正对窗户上面，一阶和三阶火箭则是正对窗户，鉴定为缩小模型后忘改玩家位置了

**Comment by Arrokoth486958** [comment]
见简介，不会发布更新，不会修复bug
同时这个模组并不是照你“鉴定”的那样，缩小了火箭模型
